version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./databaseSystem/main.sql:/docker-entrypoint-initdb.d/main.sql
    ports:
      - 5432:5432
    expose:
      - 5432
  app:
    build: ./backEndSystem
    restart: always
    volumes:
      - ./backEndSystem:/app
    working_dir: /app
    ports:
      - 3000:3000
    expose:
      - 3000
    depends_on:
      - db
