version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - ./databaseSystem/main.sql:/docker-entrypoint-initdb.d/main.sql
    ports:
      - 5432:5432
